# Front Left Knee

servo_id = 9
color = [0, 150, 255]   # Blue color
history_duration = 10.0
max_points = 1000

[pattern]
enabled = true
steps = [
    { target_angle = 50.0, duration = 1.0 },
    { target_angle = 10.0, duration = 1.0 },
]
